[opener]
mpv = [{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" }]

[open]
prepend_rules = [
  { mime = "video/*", use = [
    "mpv",
    "reveal",
  ] },
  { mime = "application/{,g}zip", use = [
    "extract",
  ] },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [
    "extract",
  ] },
]

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run = "ouch"
