[opener]
mpv = [{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" }]
mdfried = [
  { run = "mdfried %s", block = true, for = "unix", desc = "View markdown with mdfried" },
]
nvim = [
  { run = "nvim %s", block = true, for = "unix", desc = "Edit with neovim" },
]

[open]
prepend_rules = [
  { url = "*.md", use = [
    "nvim",
    "mdfried",
  ] },
  { mime = "video/*", use = [
    "mpv",
    "reveal",
  ] },
  { mime = "application/{,g}zip", use = [
    "extract",
  ] },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [
    "extract",
  ] },
]

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run = "ouch"
